'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace mx.com.paxfacturacion.testCancelar
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wcfCancelaASMXSoap", [Namespace]:="https://test.paxfacturacion.com.mx:476")>  _
    Partial Public Class wcfCancelaASMX
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private fnCancelarXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fnCancelarDistribuidoresXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Facturacion.Negocios.My.MySettings.Default.Facturacion_Negocios_mx_com_paxfacturacion_testCancelar_wcfCancelaASMX
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event fnCancelarXMLCompleted As fnCancelarXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event fnCancelarDistribuidoresXMLCompleted As fnCancelarDistribuidoresXMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.paxfacturacion.com.mx:476/fnCancelarXML", RequestNamespace:="https://test.paxfacturacion.com.mx:476", ResponseNamespace:="https://test.paxfacturacion.com.mx:476", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fnCancelarXML(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal sNombre As String, ByVal sContrasena As String) As String
            Dim results() As Object = Me.Invoke("fnCancelarXML", New Object() {sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, sNombre, sContrasena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fnCancelarXMLAsync(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal sNombre As String, ByVal sContrasena As String)
            Me.fnCancelarXMLAsync(sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, sNombre, sContrasena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fnCancelarXMLAsync(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal sNombre As String, ByVal sContrasena As String, ByVal userState As Object)
            If (Me.fnCancelarXMLOperationCompleted Is Nothing) Then
                Me.fnCancelarXMLOperationCompleted = AddressOf Me.OnfnCancelarXMLOperationCompleted
            End If
            Me.InvokeAsync("fnCancelarXML", New Object() {sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, sNombre, sContrasena}, Me.fnCancelarXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnfnCancelarXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.fnCancelarXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fnCancelarXMLCompleted(Me, New fnCancelarXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://test.paxfacturacion.com.mx:476/fnCancelarDistribuidoresXML", RequestNamespace:="https://test.paxfacturacion.com.mx:476", ResponseNamespace:="https://test.paxfacturacion.com.mx:476", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fnCancelarDistribuidoresXML(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal signature As String, ByVal sNombre As String, ByVal sContrasena As String) As String
            Dim results() As Object = Me.Invoke("fnCancelarDistribuidoresXML", New Object() {sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, signature, sNombre, sContrasena})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fnCancelarDistribuidoresXMLAsync(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal signature As String, ByVal sNombre As String, ByVal sContrasena As String)
            Me.fnCancelarDistribuidoresXMLAsync(sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, signature, sNombre, sContrasena, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fnCancelarDistribuidoresXMLAsync(ByVal sListaUUID() As String, ByVal psRFCEmisor As String, ByVal psRFCReceptor() As String, ByVal sListaTotales() As String, ByVal signature As String, ByVal sNombre As String, ByVal sContrasena As String, ByVal userState As Object)
            If (Me.fnCancelarDistribuidoresXMLOperationCompleted Is Nothing) Then
                Me.fnCancelarDistribuidoresXMLOperationCompleted = AddressOf Me.OnfnCancelarDistribuidoresXMLOperationCompleted
            End If
            Me.InvokeAsync("fnCancelarDistribuidoresXML", New Object() {sListaUUID, psRFCEmisor, psRFCReceptor, sListaTotales, signature, sNombre, sContrasena}, Me.fnCancelarDistribuidoresXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnfnCancelarDistribuidoresXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.fnCancelarDistribuidoresXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fnCancelarDistribuidoresXMLCompleted(Me, New fnCancelarDistribuidoresXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub fnCancelarXMLCompletedEventHandler(ByVal sender As Object, ByVal e As fnCancelarXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fnCancelarXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub fnCancelarDistribuidoresXMLCompletedEventHandler(ByVal sender As Object, ByVal e As fnCancelarDistribuidoresXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fnCancelarDistribuidoresXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
