'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://test.paxfacturacion.com.mx:453/webservices/wcfRecepcionASMX.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_test_wcfRecepcionASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_test_wcfRecepcionASMX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://test.paxfacturacion.com.mx:453/webservices/wcfCancelaASMX.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_testCanc_wcfCancelaASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_testCanc_wcfCancelaASMX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.paxfacturacion.com.mx:453/webservices/wcfRecepcionasmx.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_www_wcfRecepcionASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_www_wcfRecepcionASMX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.paxfacturacion.com.mx:453/webservices/wcfCancelaasmx.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_wwwCanc_wcfCancelaASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_wwwCanc_wcfCancelaASMX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ftp://192.168.2.158")>  _
        Public ReadOnly Property FacftpURL() As String
            Get
                Return CType(Me("FacftpURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ftpaccess")>  _
        Public ReadOnly Property FacftpUser() As String
            Get
                Return CType(Me("FacftpUser"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yuyin2017""")>  _
        Public ReadOnly Property FacftpPassword() As String
            Get
                Return CType(Me("FacftpPassword"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:7639/")>  _
        Public ReadOnly Property ServidorRestPruebasPruebas() As String
            Get
                Return CType(Me("ServidorRestPruebasPruebas"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.2.158:8040/")>  _
        Public ReadOnly Property ServidorRest() As String
            Get
                Return CType(Me("ServidorRest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.2.158:8040/")>  _
        Public ReadOnly Property ServidorRestCorreo() As String
            Get
                Return CType(Me("ServidorRestCorreo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.paxfacturacion.com.mx:476/webservices/wcfCancelaASMX.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_wwwCancv21_wcfCancelaASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_wwwCancv21_wcfCancelaASMX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://test.paxfacturacion.com.mx:476/webservices/wcfCancelaASMX.asmx")>  _
        Public ReadOnly Property Facturacion_Negocios_mx_com_paxfacturacion_testCancelar_wcfCancelaASMX() As String
            Get
                Return CType(Me("Facturacion_Negocios_mx_com_paxfacturacion_testCancelar_wcfCancelaASMX"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Facturacion.Negocios.My.MySettings
            Get
                Return Global.Facturacion.Negocios.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
