Imports System.Data.SqlClient

Public Class ColaboradoresReplicarDA
    Public Function ListaColaboradores(ByVal idNave As Integer, ByVal Estatus As String) As DataTable

        Dim objOperaciones As New Persistencia.OperacionesProcedimientos
        Dim consulta As String = ""
        consulta += " Select * from Nomina.Colaborador as A"
        consulta += " JOIN Nomina.ColaboradorLaboral as B on B.labo_colaboradorid=A.codr_colaboradorid"
        consulta += " JOIN Nomina.ColaboradorNomina as C on C.cono_colaboradorid=A.codr_colaboradorid"
        consulta += " JOIN nomina.ColaboradorReal as D on D.real_colaboradorid=A.codr_colaboradorid"
        'consulta += " JOIN Framework.Ciudades as E "
        'consulta += " on E.city_ciudadid=A.codr_ciudadid"
        'consulta += " JOIN Framework.Estados as F"
        'consulta += " on F.esta_estadoid=F.esta_estadoid"
        consulta += " where(B.labo_naveid = " + idNave.ToString + ") "
        consulta += " and codr_edicion='" + Estatus.ToString + "'"
        consulta += " and codr_activo='TRUE'"
        consulta += " AND C.cono_salariodiario>0"
        consulta += " ORDER BY D.real_fecha"
        Return objOperaciones.EjecutaConsulta(consulta)
    End Function

    Public Function CiudadNombre(ByVal IDCiudad As Integer) As DataTable
        Dim ObjOperaciones As New Persistencia.OperacionesProcedimientos
        Dim consulta As String = ""
        consulta += " SELECT * FROM  Framework.Ciudades as A"
        consulta += " JOIN Framework.Estados as B"
        consulta += " ON B.esta_estadoid=A.city_estadoid"
        consulta += " where city_ciudadid=" + IDCiudad.ToString
        Return ObjOperaciones.EjecutaConsulta(consulta)
    End Function


    Public Sub ReplciarColaboradoresUpdate(ByVal Colaborador As Entidades.ColaboradoresReplicar, ByVal BD As String, ByVal servidor As String)
        Dim operaciones As New Persistencia.OperacionesProcedimientos
        Dim Consulta As String = ""
        Consulta += " UPDATE [" + servidor.ToString.Trim + "].[" + BD.ToString.Trim + "].[dbo].[nom10001]"
        Consulta += " SET "
        Consulta += " idDepartamento=" + Colaborador.PDepartamentos.PDepartamentoIDNP.ToString
        Consulta += " ,idPuesto=" + Colaborador.PPuestos.PPuestoIDNP.ToString
        Consulta += " ,idtipoperiodo=2"
        Consulta += " ,idturno=5"
        Consulta += " ,codigoempleado='" + Colaborador.PColaborador.PCodigoEmpleadoNp.ToString + "'"
        Consulta += " ,fotografia=NULL"
        Consulta += " ,nombre='" + Colaborador.PColaborador.PNombre.ToString + "'"
        Consulta += " ,apellidopaterno='" + Colaborador.PColaborador.PApaterno.ToString + "'"
        Consulta += " ,apellidomaterno='" + Colaborador.PColaborador.PAmaterno.ToString + "'"
        Consulta += " ,nombrelargo='" + Colaborador.PColaborador.PNombreCompleto.ToString + "'"
        Consulta += " ,fechanacimiento='" + Colaborador.PColaborador.PFechaNacimiento.ToShortDateString + "'"
        Consulta += " ,lugarnacimiento='" + Colaborador.PCiudadesOrigen.CNombre.ToString + "'"
        Consulta += " ,estadocivil='" + Colaborador.PColaborador.PEstadoCivil.ToString + "'"
        Consulta += " ,sexo='" + Colaborador.PColaborador.PSexo.ToString + "'"
        Consulta += " ,curpi='" + Colaborador.PColaborador.PCurpI.ToString + "'"
        Consulta += " ,curpf='" + Colaborador.PColaborador.PCurpF.ToString + "'"
        Consulta += " ,numerosegurosocial='" + Colaborador.PColaboradorNomina.PNss.ToString + "'"
        Consulta += " ,umf=0"
        Consulta += " ,rfc='" + Colaborador.PColaborador.PRfc.ToString + "'"
        Consulta += " ,homoclave='" + Colaborador.PColaborador.PHomoclave.ToString + "'"
        Consulta += " ,cuentapagoelectronico=0"
        Consulta += " ,sucursalpagoelectronico=0"
        Consulta += " ,bancopagoelectronico=0"
        Consulta += " ,estadoempleado='A" + "'"
        Consulta += " ,sueldodiario=" + Colaborador.PColaboradorNomina.PSalarioDiario.ToString
        Consulta += " ,fechasueldodiario='" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,sueldovariable=0"
        Consulta += " ,fechasueldovariable='" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,sueldopromedio=0"
        Consulta += " ,fechasueldopromedio='" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,sueldointegrado=" + Colaborador.PColaboradorNomina.PSalarioIntegrado.ToString
        Consulta += " ,fechasueldointegrado='" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,calculado='TRUE'"
        Consulta += " ,afectado='FALSE'"
        Consulta += " ,calculadoextraordinario='TRUE'"
        Consulta += " ,afectadoextraordinario='FALSE'"
        Consulta += " ,interfazcheqpaqw='FALSE'"
        Consulta += " ,modificacionneto='FALSE'"
        Consulta += " ,fechaalta='" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,cuentacw=NULL"
        Consulta += " ,tipocontrato='P'"
        Consulta += " ,basecotizacionimss='F'"
        Consulta += " ,tipoempleado='S'"
        Consulta += " ,basepago='S'"
        Consulta += " ,formapago='E'"
        Consulta += " ,zonasalario='B'"
        Consulta += " ,calculoptu='TRUE'"
        Consulta += " ,calculoaguinaldo='TRUE'"
        Consulta += " ,modificacionsalarioimss='FALSE'"
        Consulta += " ,altaimss='TRUE'"
        Consulta += " ,bajaimss='FALSE'"
        Consulta += " ,cambiocotizacionimss='FALSE'"
        Consulta += " ,expediente=NULL"
        Consulta += " ,telefono=NULL"
        Consulta += " ,codigopostal=" + Colaborador.PColaborador.PCP.ToString
        Consulta += " ,direccion='" + Colaborador.PColaborador.PCalle.ToString + " " + Colaborador.PColaborador.Pnumero + "'"
        Consulta += " ,poblacion='" + Colaborador.PCiudades.CNombre.ToString + "'"
        Consulta += " ,estado='" + Colaborador.PEstados.ENombre.ToString + "'"
        Consulta += " ,nombrepadre=NULL"
        Consulta += " ,nombremadre=NULL"
        Consulta += " ,numeroafore=NULL"
        Consulta += " ,fechabaja=NULL"
        Consulta += " ,causabaja=NULL"
        Consulta += " ,sueldobaseliquidacion=NULL"
        Consulta += " ,campoextra1=NULL"
        Consulta += " ,campoextra2=NULL"
        Consulta += " ,campoextra3=NULL"
        Consulta += " ,fechareingreso=NULL"
        Consulta += " ,ajustealneto=NULL"
        Consulta += " ,timestamp=(SELECT GETDATE())"
        Consulta += " ,cidregistropatronal=1"
        Consulta += " ,ccampoextranumerico1=NULL"
        Consulta += " ,ccampoextranumerico2=NULL"
        Consulta += " ,ccampoextranumerico3=NULL"
        Consulta += " ,ccampoextranumerico4=NULL"
        Consulta += " ,ccampoextranumerico5=NULL"
        Consulta += " ,cestadoempleadoperiodo=NULL"
        Consulta += " ,cfechasueldomixto=NULL"
        Consulta += " ,csueldomixto=NULL"
        Consulta += " ,NumeroFonacot=NULL"
        Consulta += " ,CorreoElectronico=NULL"
        Consulta += " ,TipoRegimen=2"
        Consulta += " , ClabeInterbancaria=NULL"
        Consulta += " WHERE"
        Consulta += " idempleado=" + Colaborador.PColaborador.PColaboradoridNP.ToString
        operaciones.EjecutaConsulta(Consulta)
    End Sub

    Public Sub ReplciarColaboradoresInsert(ByVal Colaborador As Entidades.ColaboradoresReplicar, ByVal BD As String, ByVal servidor As String)
        Dim operaciones As New Persistencia.OperacionesProcedimientos
        Dim Consulta As String = ""

        Consulta += " INSERT INTO  [" + servidor.ToString.Trim + "].[" + BD.ToString.Trim + "].[dbo].[nom10001]"
        Consulta += " ("
        Consulta += " idDepartamento"
        Consulta += " ,idPuesto"
        Consulta += " ,idtipoperiodo"
        Consulta += " ,idturno"
        Consulta += " ,codigoempleado"
        Consulta += " ,fotografia"
        Consulta += " ,nombre"
        Consulta += " ,apellidopaterno"
        Consulta += " ,apellidomaterno"
        Consulta += " ,nombrelargo"
        Consulta += " ,fechanacimiento"
        Consulta += " ,lugarnacimiento"
        Consulta += " ,estadocivil"
        Consulta += " ,sexo"
        Consulta += " ,curpi"
        Consulta += " ,curpf"
        Consulta += " ,numerosegurosocial"
        Consulta += " ,umf"
        Consulta += " ,rfc"
        Consulta += " ,homoclave"
        Consulta += " ,cuentapagoelectronico"
        Consulta += " ,sucursalpagoelectronico"
        Consulta += " ,bancopagoelectronico"
        Consulta += " ,estadoempleado"
        Consulta += " ,sueldodiario"
        Consulta += " ,fechasueldodiario"
        Consulta += " ,sueldovariable"
        Consulta += " ,fechasueldovariable"
        Consulta += " ,sueldopromedio"
        Consulta += " ,fechasueldopromedio"
        Consulta += " ,sueldointegrado"
        Consulta += " ,fechasueldointegrado"
        Consulta += " ,calculado"
        Consulta += " ,afectado"
        Consulta += " ,calculadoextraordinario"
        Consulta += " ,afectadoextraordinario"
        Consulta += " ,interfazcheqpaqw"
        Consulta += " ,modificacionneto"
        Consulta += " ,fechaalta"
        Consulta += " ,cuentacw"
        Consulta += " ,tipocontrato"
        Consulta += " ,basecotizacionimss"
        Consulta += " ,tipoempleado"
        Consulta += " ,basepago"
        Consulta += " ,formapago"
        Consulta += " ,zonasalario"
        Consulta += " ,calculoptu"
        Consulta += " ,calculoaguinaldo"
        Consulta += " ,modificacionsalarioimss"
        Consulta += " ,altaimss"
        Consulta += " ,bajaimss"
        Consulta += " ,cambiocotizacionimss"
        Consulta += " ,expediente"
        Consulta += " ,telefono"
        Consulta += " ,codigopostal"
        Consulta += " ,direccion"
        Consulta += " ,poblacion"
        Consulta += " ,estado"
        Consulta += " ,nombrepadre"
        Consulta += " ,nombremadre"
        Consulta += " ,numeroafore"
        Consulta += " ,fechabaja"
        Consulta += " ,causabaja"
        Consulta += " ,sueldobaseliquidacion"
        Consulta += " ,campoextra1"
        Consulta += " ,campoextra2"
        Consulta += " ,campoextra3"
        Consulta += " ,fechareingreso"
        Consulta += " ,ajustealneto"
        Consulta += " ,timestamp"
        Consulta += " ,cidregistropatronal"
        Consulta += " ,ccampoextranumerico1"
        Consulta += " ,ccampoextranumerico2"
        Consulta += " ,ccampoextranumerico3"
        Consulta += " ,ccampoextranumerico4"
        Consulta += " ,ccampoextranumerico5"
        Consulta += " ,cestadoempleadoperiodo"
        Consulta += " ,cfechasueldomixto"
        Consulta += " ,csueldomixto"
        Consulta += " ,NumeroFonacot"
        Consulta += " ,CorreoElectronico"
        Consulta += " ,TipoRegimen"
        Consulta += " , ClabeInterbancaria"
        Consulta += " )"
        Consulta += " VALUES"
        Consulta += " ("
        Consulta += "" + Colaborador.PDepartamentos.PDepartamentoIDNP.ToString
        Consulta += " ," + Colaborador.PPuestos.PPuestoIDNP.ToString
        Consulta += " ,2"
        Consulta += " ,5"
        Consulta += " ,'" + Colaborador.PColaborador.PCodigoEmpleadoNp.ToString + "'"
        Consulta += " ,NULL"
        Consulta += " ,'" + Colaborador.PColaborador.PNombre.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PApaterno.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PAmaterno.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PNombreCompleto.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PFechaNacimiento.ToShortDateString + "'"
        Consulta += " ,'" + Colaborador.PCiudadesOrigen.CNombre.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PEstadoCivil.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PSexo.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PCurpI.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PCurpF.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PNss.ToString + "'"
        Consulta += " ,0"
        Consulta += " ,'" + Colaborador.PColaborador.PRfc.ToString + "'"
        Consulta += " ,'" + Colaborador.PColaborador.PHomoclave.ToString + "'"
        Consulta += " ,0"
        Consulta += " ,0"
        Consulta += " ,0"
        Consulta += " ,'A'"
        Consulta += " ," + Colaborador.PColaboradorNomina.PSalarioDiario.ToString
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,0"
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,0"
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ," + Colaborador.PColaboradorNomina.PSalarioIntegrado.ToString
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,'TRUE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'TRUE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'" + Colaborador.PColaboradorNomina.PFechaAltaImss.ToShortDateString + "'"
        Consulta += " ,NULL"
        Consulta += " ,'P'"
        Consulta += " ,'F'"
        Consulta += " ,'S'"
        Consulta += " ,'S'"
        Consulta += " ,'E'"
        Consulta += " ,'B'"
        Consulta += " ,'TRUE'"
        Consulta += " ,'TRUE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'TRUE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,'FALSE'"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ," + Colaborador.PColaborador.PCP.ToString
        Consulta += " ,'" + Colaborador.PColaborador.PCalle.ToString + " " + Colaborador.PColaborador.Pnumero + "'"
        Consulta += " ,'" + Colaborador.PCiudades.CNombre.ToString + "'"
        Consulta += " ,'" + Colaborador.PEstados.ENombre.ToString + "'"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,(SELECT GETDATE())"
        Consulta += " ," + Colaborador.PPatrones.PNpatronalNP.ToString
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,NULL"
        Consulta += " ,2"
        Consulta += " ,NULL"
        Consulta += " )"
        operaciones.EjecutaConsulta(Consulta)
    End Sub

    Public Sub ReplicarNominpaqSay(ByVal idNave As Integer, ByVal BD As String, ByVal Servidor As String)
        Dim operaciones As New Persistencia.OperacionesProcedimientos
        Dim consulta As String = ""
        consulta += " UPDATE Nomina.Colaborador"
        consulta += " SET "
        consulta += " codr_nominpaqID = A.idempleado,"
        consulta += " codr_CodigoEmpleadoNP=A.codigoempleado"
        consulta += " FROM [" + Servidor.ToString.Trim + "].[" + BD.ToString.Trim + "].[dbo].[nom10001] as A"
        consulta += " JOIN Nomina.ColaboradorNomina as B "
        consulta += " JOIN Nomina.Colaborador as C on C.codr_colaboradorid=B.cono_colaboradorid"
        consulta += " JOIN Nomina.ColaboradorLaboral as D  on D.labo_colaboradorid=B.cono_colaboradorid"
        consulta += " ON B.cono_nss=A.numerosegurosocial"
        consulta += " WHERE"
        'consulta += " codr_edicion = 1 and"
        consulta += " codr_activo=1"
        consulta += " and D.labo_naveid=" + idNave.ToString
        operaciones.EjecutaConsulta(consulta)
    End Sub

    Public Sub ActualizarEditar(ByVal idColaborador As Integer)
        Dim operaciones As New Persistencia.OperacionesProcedimientos
        Dim consulta As String = ""
        consulta += " UPDATE Nomina.Colaborador"
        consulta += " set codr_edicion='FALSE'"
        consulta += " where codr_colaboradorid =" + idColaborador.ToString
        operaciones.EjecutaConsulta(consulta)
    End Sub

    Public Function validarCodigoEmpleadoNPSAY(ByVal codigoEmpleado As String, ByVal BD As String, ByVal Servidor As String) As DataTable
        Dim operaciones As New Persistencia.OperacionesProcedimientos
        Dim consulta As String = ""
        consulta += "SELECT nombrelargo "
        consulta += " FROM [" + Servidor.ToString.Trim + "].[" + BD.ToString.Trim + "].[dbo].[nom10001]"
        consulta += "where codigoempleado='" + codigoEmpleado.ToString + "'"
        Return operaciones.EjecutaConsulta(consulta)
    End Function
End Class
